project:
  type: website
  resources:
    - downloads/
website:
  title: "example-download"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



